### ISSUE TITLE
[BUG] Property does not exist on serve()

### ISSUE THREAD

**Issue by ellisio** [inngest/inngest-js#340]
**Describe the bug**

When upgrading to v3.0.0, we're getting a typing error:

```
Property 'PUT' does not exist on type '(req: Either<NextApiRequest, NextRequest>, res: NextApiResponse) => Promise<Response | undefined>'.ts(2339)
```

This is how we have our client defined:

```
import { serve } from "inngest/next";
import { functions, inngest } from "@/inngest";

export const { GET, POST, PUT } = serve({
  client: inngest,
  functions,
});
```

**To Reproduce**

1. Install `inngest@3.0.0` in a TypeScript NextJS 13 project.
2. Initialize the client (see above).
  - Note: You can just use an empty `functions: []` definition, same thing.

**Expected behavior**
Should not have a typing error.

**Code snippets / Logs / Screenshots**
![image](https://github.com/inngest/inngest-js/assets/127468/1e299b7f-4ebd-4601-8987-3609ca059269)

**System info (please complete the following information):**

- OS: Man/Linux
- npm package Version: 3.0.0
- Framework: Next.js
- Platform: Local, Vercel

**Comment by jpwilliams** [comment]
Thanks for the report, @ellisio! Sorry you've run into this.

A workaround for the moment is to revert the v2 functionality of treating `serve()` as `any`:
```ts
export const { GET, POST, PUT } = serve(...) as any;
```

There's a couple of fixes needed here - one is #339 and the other just needs to be an app router integration test! Let me work on that now. 🙂

**Comment by ellisio** [comment]
@jpwilliams Was just in the middle of typing out the `as any` fix myself, thank you!

**Comment by tonyhb** [comment]
Should be fixed in 3.0.1 - thank you!
