### PR TITLE
Fix `"inngest/next"` types not inferring from `defineProperties`

### LINKED ISSUE #340: [BUG] Property does not exist on serve()
**Describe the bug**

When upgrading to v3.0.0, we're getting a typing error:

```
Property 'PUT' does not exist on type '(req: Either<NextApiRequest, NextRequest>, res: NextApiResponse) => Promise<Response | undefined>'.ts(2339)
```

This is how we have our client defined:

```
import { serve } from "inngest/next";
import { functions, inngest } from "@/inngest";

export const { GET, POST, PUT } = serve({
  client: inngest,
  functions,
});
```

**To Reproduce**

1. Install `inngest@3.0.0` in a TypeScript NextJS 13 project.
2. Initialize the client (see above).
  - Note: You can just use an empty `functions: []` definition, same thing.

**Expected behavior**
Should not have a typing error.

**Code snippets / Logs / Screenshots**
image

**System info (please complete the following information):**

- OS: Man/Linux
- npm package Version: 3.0.0
- Framework: Next.js
- Platform: Local, Vercel

### PR DESCRIPTION
**Pull request by jpwilliams**
## Summary

Fixes #340, ensuring the return type of `"inngest/next"`'s `serve()` is correctly inferred.

Fuller integration tests for the app router will come in #341.

## Checklist

- [ ] ~~Added a [docs PR](https://github.com/inngest/website) that references this PR~~ N/A
- [ ] ~~Added unit/integration tests~~ N/A #341
- [x] Added changesets if applicable

## Related

- Fixes #340

### CODE REVIEW

**Review by djfarrelly — COMMENTED** [review]
LGTM - Weird typescript stuff on this one!

**Comment by jpwilliams** [comment]
> @djfarrelly: LGTM - Weird typescript stuff on this one!

Yeah. v2 got away with this because we always returned `any`. #341 adds integration tests for the app router which will catch this in the future.
